### PR TITLE
Terraria Mobile Support

### PR DESCRIPTION
**Pull request by sclark-dev**
This is meant for a new branch that provides support for those looking to set up a server for the mobile version of Terraria. The server is ran in an identical way to the PC version, it just needs a different set of server files.

This should be fully functional, however I don't actually own a copy of Terraria for mobile so I cannot actually test it.

### CODE REVIEW

**Comment by ich777** [comment]
@sclark-dev is the mobile server now finally available for Linux? To my knowledge the mobile server was for Windows only…

**Comment by ich777** [comment]
I will test this ASAP, please give me a bit, I'm currently really busy in real life... :/

**Comment by ich777** [comment]
@sclark-dev Thank you for the PR, I hope you are okay with the changes I've made, will build the Docker ASAP, have to first merge everything into my private Git repo and then build it.
Should not take more than 10 minutes... :)

Everything is working fine! Thank you again!

**Comment by ich777** [comment]
@sclark-dev BTW are you sure that the volume in the `docker-compose.yml` is set correctly?

**Comment by sclark-dev** [comment]
@ich777 Yes, the volume just uses the default docker location. Main reason for giving it an actual name is so it's not assigned some random long string you have to memorize to manually change files.

**Pull request merged**
